name: Get release version from tag

on:
  workflow_call:
    outputs:
      release-version:
        description: "Generate a release version from the current tag"
        value: ${{ jobs.get-version-from-tag.outputs.release-version }}

jobs:
  get-version-from-tag:
    runs-on: ubuntu-latest
    outputs:
      release-version: ${{ steps.release-version.outputs.release-version }}
    steps:
      - name: Set release version
        id: release-version
        run: echo "release-version=${GITHUB_REF#refs/*/v}" >> $GITHUB_OUTPUT
