name: Get release version from tag

on:
  workflow_call:
    outputs:
      release-version:
        description: "Generate a release version from the current tag"
        value: ${{ jobs.get-version-from-tag.outputs.release-version }}

jobs:
  get-version-from-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Set release version
        run: echo -n "release-version=${GITHUB_REF#refs/*/v}" >> $GITHUB_OUTPUT
